# Generated by Codex on 2026-06-01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ai_content_agent", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostGenerationBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=120)),
                ("niche", models.CharField(max_length=120)),
                ("objective", models.CharField(max_length=160)),
                ("tone", models.CharField(max_length=80)),
                ("theme", models.CharField(max_length=160)),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                ("strategy_summary", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_generation_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="postgeneration",
            name="idea",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="postgeneration",
            name="image_text",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="postgeneration",
            name="image_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="postgeneration",
            name="post_order",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="postgeneration",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="ai_content_agent.postgenerationbatch",
            ),
        ),
    ]
