# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_content_agent", "0002_postgenerationbatch_postgeneration_batch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postgenerationbatch",
            name="use_templates",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="postgeneration",
            name="template",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
