# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ai_content_agent",
            "0003_postgeneration_template_and_batch_use_templates",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="postgeneration",
            name="scheduled_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
