# Generated by Django 4.2.9 on 2026-06-03 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_content_agent', '0008_postgenerationbatch_logo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=120)),
                ('niche', models.CharField(max_length=120)),
                ('reference_image_1', models.ImageField(blank=True, null=True, upload_to='content_agent/brand_references/')),
                ('reference_image_2', models.ImageField(blank=True, null=True, upload_to='content_agent/brand_references/')),
                ('reference_image_1_url', models.CharField(blank=True, max_length=500)),
                ('reference_image_2_url', models.CharField(blank=True, max_length=500)),
                ('logo_url', models.CharField(blank=True, max_length=500)),
                ('visual_identity_summary', models.TextField(blank=True)),
                ('visual_identity_prompt', models.TextField(blank=True)),
                ('primary_color', models.CharField(default='#006C44', max_length=7)),
                ('secondary_color', models.CharField(default='#1FD794', max_length=7)),
                ('tertiary_color', models.CharField(default='#98C8B6', max_length=7)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('text_font', models.CharField(blank=True, max_length=80)),
                ('logo_position', models.CharField(default='bottom_right', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_agent_brands', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='postgeneration',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='ai_content_agent.brand'),
        ),
        migrations.AddField(
            model_name='postgenerationbatch',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='ai_content_agent.brand'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['user', 'business_name', 'niche'], name='ai_content__user_id_c034a5_idx'),
        ),
    ]
