# Generated by Django 4.2.9 on 2026-06-09 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_content_agent', '0012_generationstatus_pending_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='postbatch',
            name='image_source',
            field=models.CharField(default='ai', max_length=20),
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ai_post_image', 'AI post image')], max_length=40)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='ai_content_agent.postbatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_agent_usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'kind', 'created_at'], name='ai_content__user_id_85891b_idx')],
            },
        ),
    ]
