# Generated by Django 4.2.9 on 2026-07-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_content_agent', '0019_usageevent_user_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usageevent',
            name='kind',
            field=models.CharField(choices=[('ai_post_image', 'AI post image'), ('user_post_image', 'User post image'), ('ai_image_edit', 'AI image edit')], max_length=40),
        ),
    ]
