# Generated by Django 4.2.9 on 2026-07-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_content_agent', '0020_alter_usageevent_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_edit_mode',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
