from django.urls import path

from .views import (
    BrandDetailAPIView,
    BrandListAPIView,
    BrandReferenceUploadCompleteAPIView,
    BrandReferenceUploadSignAPIView,
    BrandVisualIdentityJobAPIView,
    ApprovePostPromptsAPIView,
    CalendarPostsAPIView,
    ContentAgentUsageAPIView,
    DeletePostAPIView,
    DownloadPostImageAPIView,
    FirebaseCleanupMaintenanceAPIView,
    GeneratePostContentAPIView,
    PendingReviewPostBatchAPIView,
    PostGenerationJobAPIView,
    PostImageGenerationJobAPIView,
    PostGenerationStatusAPIView,
    PostSourceUploadSignAPIView,
    RerenderPostImageAPIView,
)

urlpatterns = [
    path(
        "jobs/post-generation/",
        PostGenerationJobAPIView.as_view(),
        name="post-generation-job",
    ),
    path(
        "jobs/post-images/",
        PostImageGenerationJobAPIView.as_view(),
        name="post-image-generation-job",
    ),
    path(
        "jobs/brand-visual-identity/",
        BrandVisualIdentityJobAPIView.as_view(),
        name="brand-visual-identity-job",
    ),
    path(
        "uploads/post-source-images/sign/",
        PostSourceUploadSignAPIView.as_view(),
        name="post-source-upload-sign",
    ),
    path(
        "uploads/brand-references/sign/",
        BrandReferenceUploadSignAPIView.as_view(),
        name="brand-reference-upload-sign",
    ),
    path(
        "uploads/brand-references/complete/",
        BrandReferenceUploadCompleteAPIView.as_view(),
        name="brand-reference-upload-complete",
    ),
    path(
        "brands/",
        BrandListAPIView.as_view(),
        name="brand-list",
    ),
    path(
        "brands/<int:brand_id>/",
        BrandDetailAPIView.as_view(),
        name="brand-detail",
    ),
    path(
        "posts/generate/",
        GeneratePostContentAPIView.as_view(),
        name="generate-post-content",
    ),
    path(
        "posts/generate/<int:batch_id>/status/",
        PostGenerationStatusAPIView.as_view(),
        name="post-generation-status",
    ),
    path(
        "posts/generate/<int:batch_id>/approve/",
        ApprovePostPromptsAPIView.as_view(),
        name="approve-post-prompts",
    ),
    path(
        "posts/review/",
        PendingReviewPostBatchAPIView.as_view(),
        name="pending-review-post-batch",
    ),
    path(
        "posts/calendar/",
        CalendarPostsAPIView.as_view(),
        name="calendar-posts",
    ),
    path(
        "usage/",
        ContentAgentUsageAPIView.as_view(),
        name="content-agent-usage",
    ),
    path(
        "maintenance/firebase-cleanup/",
        FirebaseCleanupMaintenanceAPIView.as_view(),
        name="firebase-cleanup-maintenance",
    ),
    path(
        "posts/<int:post_id>/render/",
        RerenderPostImageAPIView.as_view(),
        name="rerender-post-image",
    ),
    path(
        "posts/<int:post_id>/",
        DeletePostAPIView.as_view(),
        name="delete-post",
    ),
    path(
        "posts/<int:post_id>/download/",
        DownloadPostImageAPIView.as_view(),
        name="download-post-image",
    ),
]
