"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
import tempfile
from dotenv import load_dotenv
from pathlib import Path
from datetime import timedelta
from utils.env import get_neon_pooler_host, is_production

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-5.4-mini")
OPENAI_IMAGE_MODEL = os.getenv("OPENAI_IMAGE_MODEL", "gpt-image-1")
CONTENT_AGENT_USE_MOCK_IMAGES = (
    os.getenv("CONTENT_AGENT_USE_MOCK_IMAGES", "true").lower() == "true"
)
CONTENT_AGENT_STORAGE_BACKEND = os.getenv(
    "CONTENT_AGENT_STORAGE_BACKEND",
    "local",
)
CONTENT_AGENT_FONT_DIR = os.getenv(
    "CONTENT_AGENT_FONT_DIR",
    str(BASE_DIR / "ai_content_agent" / "fonts"),
)
FIREBASE_STORAGE_BUCKET = os.getenv("FIREBASE_STORAGE_BUCKET", "")
FIREBASE_PUBLIC_BASE_URL = os.getenv("FIREBASE_PUBLIC_BASE_URL", "")
FIREBASE_SIGNED_UPLOAD_EXPIRATION_SECONDS = int(
    os.getenv("FIREBASE_SIGNED_UPLOAD_EXPIRATION_SECONDS", "600")
)
FIREBASE_SIGNED_READ_EXPIRATION_SECONDS = int(
    os.getenv("FIREBASE_SIGNED_READ_EXPIRATION_SECONDS", "600")
)
CONTENT_AGENT_MAINTENANCE_TOKEN = os.getenv(
    "CONTENT_AGENT_MAINTENANCE_TOKEN",
    os.getenv("CRON_SECRET", ""),
)
QSTASH_TOKEN = os.getenv("QSTASH_TOKEN", "")
CONTENT_AGENT_JOB_TOKEN = os.getenv("CONTENT_AGENT_JOB_TOKEN", "")
CONTENT_AGENT_PUBLIC_URL = os.getenv("CONTENT_AGENT_PUBLIC_URL", "")

if not CONTENT_AGENT_PUBLIC_URL:
    vercel_public_host = (
        os.getenv("VERCEL_PROJECT_PRODUCTION_URL")
        or os.getenv("VERCEL_URL")
    )
    if vercel_public_host:
        CONTENT_AGENT_PUBLIC_URL = f"https://{vercel_public_host}"

if is_production(): 
    DEBUG = False
    # Vercel Functions only provide ephemeral writable storage. Persistent
    # media lives in Firebase; this directory is just a processing workspace.
    MEDIA_ROOT = Path(tempfile.gettempdir()) / "django-apis-media"
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('NEON_DB_NAME'),
            'USER': os.getenv('NEON_DB_USER'),
            'PASSWORD': os.getenv('NEON_DB_PASSWORD'),
            'HOST': (
                os.getenv('NEON_DB_POOL_HOST')
                or get_neon_pooler_host(os.getenv('NEON_DB_HOST'))
            ),
            'PORT': os.getenv('NEON_DB_PORT', '5432'),
            'CONN_MAX_AGE': 0,
            'DISABLE_SERVER_SIDE_CURSORS': True,
            'OPTIONS': {
                'sslmode': 'require',
            },
        }
    }
    # TODO: pegar chaves de pagamento reais para produção
    # STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
    # STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")
    # STRIPE_CHECKOUT_SUCCESS_URL = os.getenv("STRIPE_CHECKOUT_SUCCESS_URL", "")
    # STRIPE_CHECKOUT_CANCEL_URL = os.getenv("STRIPE_CHECKOUT_CANCEL_URL", "")
    CONTENT_AGENT_USE_MOCK_CONTENT = False
    ALLOWED_HOSTS = [
        'django-apis-two.vercel.app',
        '.maisappreis-projects.vercel.app',
        '.vercel.app',
    ]
    PASSWORD_RESET_CONFIRM_URL = os.getenv(
        "PASSWORD_RESET_CONFIRM_URL",
        "https://maisappreis.github.io/axis/reset-password",
    )
    DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@axis.com")
    EMAIL_BACKEND = os.getenv(
        "EMAIL_BACKEND",
        "django.core.mail.backends.smtp.EmailBackend",
    )
    EMAIL_HOST = os.getenv("EMAIL_HOST", "localhost")
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "25"))
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
    EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "false").lower() == "true"
    EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "false").lower() == "true"
    FIREBASE_CREDENTIALS_JSON = os.getenv("FIREBASE_CREDENTIALS_JSON", "")
    CONTENT_AGENT_QUEUE_BACKEND = os.getenv("CONTENT_AGENT_QUEUE_BACKEND", "qstash")
else:
    DEBUG = True
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / "database.sqlite3",
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
        }
    }
    STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY_DEV", "")
    STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET_DEV", "")
    STRIPE_CHECKOUT_SUCCESS_URL = os.getenv("STRIPE_CHECKOUT_SUCCESS_URL_DEV", "")
    STRIPE_CHECKOUT_CANCEL_URL = os.getenv("STRIPE_CHECKOUT_CANCEL_URL_DEV", "")
    CONTENT_AGENT_USE_MOCK_CONTENT = (
        os.getenv("CONTENT_AGENT_USE_MOCK_CONTENT", "true").lower() == "true"
    )
    ALLOWED_HOSTS = ['*']
    PASSWORD_RESET_CONFIRM_URL = os.getenv(
        "PASSWORD_RESET_CONFIRM_URL_DEV",
        "http://localhost:3000/axis/reset-password",
    )
    DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL_DEV", "no-reply@axis.local")
    EMAIL_BACKEND = os.getenv(
        "EMAIL_BACKEND_DEV",
        "django.core.mail.backends.console.EmailBackend",
    )
    EMAIL_HOST = os.getenv("EMAIL_HOST_DEV", "localhost")
    EMAIL_PORT = int(os.getenv("EMAIL_PORT_DEV", "25"))
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER_DEV", "")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD_DEV", "")
    EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS_DEV", "false").lower() == "true"
    EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL_DEV", "false").lower() == "true"
    FIREBASE_CREDENTIALS_PATH = os.getenv("FIREBASE_CREDENTIALS_PATH", "")
    CONTENT_AGENT_QUEUE_BACKEND = os.getenv("CONTENT_AGENT_QUEUE_BACKEND", "inline")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',
    'drf_spectacular',
    'corsheaders',

    'accounts',
    'upfit_gym',
    'dental_clinic',
    'print3d',
    'axis',
    'ai_core',
    'ai_content_agent',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
    "http://localhost:8081",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "https://maisappreis.github.io"
]

CORS_ALLOW_HEADERS = [
    'Authorization',
    'Content-Type',
    'X-Requested-With',
    'X-CSRFToken',
]

ROOT_URLCONF = 'config.urls'
# LOGIN_URL = '/api/accounts/login'
LOGIN_REDIRECT_URL = '/api'

# CSRF_COOKIE_NAME = 'csrftoken'
# CSRF_COOKIE_HTTPONLY = False
# CSRF_COOKIE_SAMESITE = 'None'
# CSRF_COOKIE_SECURE = True
# CSRF_COOKIE_HTTPONLY = True

SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True

CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:5173',
    'http://localhost:5173',
    'http://localhost:3000',
    'https://maisappreis.github.io'
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Django APIs for Web Application',
    'DESCRIPTION': 'APIs for some web applications',
    'VERSION': '1.0.0',
}
