# Generated by Django 4.2.9 on 2024-08-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('nf', models.BooleanField(default=False)),
                ('procedure', models.CharField(max_length=255)),
                ('payment', models.CharField(max_length=255)),
                ('installments', models.IntegerField()),
                ('value', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('date', 'name', 'procedure', 'value')},
            },
        ),
        migrations.CreateModel(
            name='ExpenseTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('installments', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('is_paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('name', 'year', 'month', 'value')},
            },
        ),
    ]
