# Generated by Django 4.2.9 on 2024-09-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_clinic', '0004_monthclosing_monthclosingtest_revenue_net_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthclosing',
            name='card_value_next_month',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='monthclosingtest',
            name='card_value_next_month',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='revenue',
            name='release_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='revenuetest',
            name='release_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
