# Generated by Django 4.2.9 on 2026-03-10 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dental_clinic', '0005_monthclosing_card_value_next_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Agenda',
        ),
        migrations.RenameField(
            model_name='monthclosing',
            old_name='profit',
            new_name='net_profit',
        ),
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='revenue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthclosing',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revenue',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='installments',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthclosing',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthclosing',
            name='bank_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthclosing',
            name='card_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthclosing',
            name='card_value_next_month',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthclosing',
            name='cash_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthclosing',
            name='other_revenue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthclosing',
            name='reference',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='installments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='net_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'year', 'month', 'value'), name='unique_expense_per_user'),
        ),
        migrations.AddConstraint(
            model_name='monthclosing',
            constraint=models.UniqueConstraint(fields=('user', 'reference', 'month', 'year'), name='unique_month_closing_per_user'),
        ),
        migrations.AddConstraint(
            model_name='revenue',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'name', 'procedure', 'value'), name='unique_revenue_per_user'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'date', 'time'), name='unique_appointment_per_user'),
        ),
    ]
