# Generated by Django 4.2.9 on 2026-03-10 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dental_clinic', '0006_appointment_delete_agenda_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgendaTest',
        ),
        migrations.DeleteModel(
            name='ExpenseTest',
        ),
        migrations.DeleteModel(
            name='MonthClosingTest',
        ),
        migrations.DeleteModel(
            name='RevenueTest',
        ),
    ]
