# Generated by Django 4.2.9 on 2024-08-12 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=2)),
                ('start', models.DateField()),
                ('plan', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
                ('value', models.FloatField()),
                ('paid', models.CharField(choices=[('À pagar', 'À pagar'), ('Pago', 'Pago')], default='À pagar', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('name', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=50)),
                ('payment_day', models.IntegerField()),
                ('value', models.FloatField()),
                ('paid', models.CharField(choices=[('À pagar', 'À pagar'), ('Link enviado', 'Link enviado'), ('Pago', 'Pago')], default='À pagar', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upfit_gym.customer')),
            ],
            options={
                'unique_together': {('customer', 'year', 'month')},
            },
        ),
    ]
