# Generated by Django 4.2.9 on 2024-08-16 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upfit_gym', '0002_expensetest_customertest_revenuetest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuetest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upfit_gym.customertest'),
        ),
    ]
