# Generated by Django 4.2.9 on 2024-08-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upfit_gym', '0003_alter_revenuetest_customer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together={('name', 'year', 'month', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='expensetest',
            unique_together={('name', 'year', 'month', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='revenue',
            unique_together={('customer', 'year', 'month', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='revenuetest',
            unique_together={('customer', 'year', 'month', 'value')},
        ),
    ]
