# Generated by Django 4.2.9 on 2024-08-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upfit_gym', '0004_alter_expense_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='installments',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='expensetest',
            name='installments',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
