# Generated by Django 4.2.9 on 2024-08-30 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upfit_gym', '0005_expense_installments_expensetest_installments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='due_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='expensetest',
            old_name='due_date',
            new_name='date',
        ),
    ]
