# Generated by Django 4.2.9 on 2026-03-12 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upfit_gym', '0006_rename_due_date_expense_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='revenue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upfit_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upfit_expense', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revenue',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upfit_revenue', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_customer_per_user_upfit'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'year', 'month', 'value'), name='unique_expense_per_user_per_month_year'),
        ),
        migrations.AddConstraint(
            model_name='revenue',
            constraint=models.UniqueConstraint(fields=('user', 'customer', 'year', 'month', 'value'), name='unique_revenue_per_user_per_month_year'),
        ),
    ]
