# Generated by Django 4.2.9 on 2026-03-12 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upfit_gym', '0007_alter_customer_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customertest',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='ExpenseTest',
        ),
        migrations.AlterUniqueTogether(
            name='revenuetest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='revenuetest',
            name='customer',
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='upfit_customer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='upfit_expense', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='revenue',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='upfit_revenue', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CustomerTest',
        ),
        migrations.DeleteModel(
            name='RevenueTest',
        ),
    ]
